# For every push to the master branch, this publishes an NPM package to the
# "unstable" NPM tag.

name: Publish Unstable

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: publish-unstable-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: "NPM Publish"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          # This creates an .npmrc that reads the NODE_AUTH_TOKEN environment variable
          node-registry-url: 'https://registry.npmjs.org'

      - name: build
        run: pnpm build

      - name: set versions
        run: node ./workspace/unstable-release/src/version.js

      - name: npm publish
        run: node ./workspace/unstable-release/src/publish.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
